defaults:
  - _self_
  - model: dit
  - data: multi_latent_pretrain
  - trainer: dit_mix_pretrain
  

wandb_project: "MGE-LDM-DIT"


seed: 42
ckpt_path: null
save_dir: null

autoencoder_ckpt_path: "/data2/yoongi/MGE_LDM/default_ae/checkpoints/unwrapped_last.ckpt"


batch_size: 64
num_workers: 32

mixture_only_pretraining: true
pretrained_ckpt_path: null 