
defaults:
  - _self_
  - model: autoencoder
  - data: single
  - trainer: autoencoder

wandb_project: "MGE-LDM-Autoencoder"

seed: 42
ckpt_path: null
pretrained_ckpt_path: null
save_dir: null


batch_size: 16
num_workers: 16
